// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"curriculum/service/media/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/medium/transform",
				Handler: ApiHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
